export enum ProductCategory {
  SINGLE_MONUMENTS = "single-monuments",
  DOUBLE_MONUMENTS = "double-monuments",
  TRIPLE_MONUMENTS = "triple-monuments",
  MILITARY_MONUMENTS = "military-monuments",
  CHILDREN_MONUMENTS = "children-monuments",
  VASES = "vases",
  GRANITE_BALLS = "granite-balls",
  LAMPS = "lamps",
  COVERS = "covers",
  POLYMER_CORNERS = "polymer-corners",
  GRANITE_CORNERS = "granite-corners",
  WINDOWSILLS = "windowsills",
  COUNTERTOPS = "countertops",
  STAIRS = "stairs",
  PAVING = "paving",
  BALUSTRADES = "balustrades",
}
